# CodeRabbit Configuration for FC2X Project
# See: https://docs.coderabbit.ai/configure/configuration-via-yaml-file/
# Best practice: Version-controlled configuration in repository root

# Review instructions - CodeRabbit will follow these guidelines
review_instructions: |
  This project implements OAuth 2.0 PKCE flow for Twitter/X authentication in a Next.js TypeScript application.
  
  Focus areas:
  - Security: Proper PKCE implementation (code verifier/challenge), secure token storage and handling, webhook signature verification
  - Error handling: Comprehensive error handling in authentication flows, proper error messages and logging
  - Database security: SQL injection prevention using parameterized queries, secure connection handling
  - Token management: OAuth 2.0 token refresh logic, expiration handling, secure storage
  - API design: RESTful API routes, proper HTTP status codes, request/response validation
  - TypeScript: Type safety, proper typing, avoiding any types
  - Next.js: Proper use of Next.js API routes, server components, and best practices
  
  Pay special attention to:
  - OAuth 2.0 PKCE flow correctness in src/app/api/auth/route.ts
  - Token exchange and validation in src/app/api/callback/route.ts
  - Webhook security and token refresh in src/app/api/webhook/route.ts
  - Environment variable security and usage
  - Database query parameterization to prevent SQL injection

